logger:
  writer: stdout
  level: error
tor:
  req_type: GET
  url: https://bridges.torproject.org/bridges?transport=obfs4
output:
  file_name: bridge.txt
client:
  timeout: 10
  max_idle_conns: 10
  idle_conn_timeout: 30
  disable_keep_alives: false
context_timeout: 5
